baseURL = "https://twigleingrid.github.io"
languageCode = "en-us"
title = "Ingrid's World"
theme = "ananke"
publishDir = ".."


[params]
  twitter = "https://twitter.com/BudauIngrid"
  github = "https://github.com/twigleingrid"
  linkedin = "https://www.linkedin.com/in/ingrid-budau-a11218190/"
  facebook = "https://www.facebook.com/ingrid.budau.7"
  featured_image = "/images/Blossoming_cherry_trees.jpg"
  description = ""
  background_color_class = "bg-black"
  recent_posts_number = 2
